const { NativeFunction, ArgType } = require("@tryforge/forgescript");
const { request } = require("../../pterodactyl");

exports.default = new NativeFunction({
    name: "$enableTwoFactor",
    version: "1.2.0",
    description: "Enables TOTP two-factor authentication using QR code generated by GET request",
    output: ArgType.Json,
    brackets: true,
    unwrap: true,
    args: [
        {
            name: "variable",
            description: "Configuration variable name",
            type: ArgType.String,
            required: true,
            rest: false
        },
        {
            name: "code",
            description: "TOTP code from app",
            type: ArgType.String,
            required: true,
            rest: false
        }
    ],
    async execute(ctx, [variable, code]) {
        return this.successJSON(await request(variable, "POST", "/account/two-factor", JSON.stringify({ code })));
    }
});