const { NativeFunction, ArgType } = require("@tryforge/forgescript");
const { request } = require("../../pterodactyl");

exports.default = new NativeFunction({
    name: "$enableTwoFactor",
    version: "1.0.0",
    description: "Enables TOTP two-factor authentication using QR code generated by GET request",
    output: ArgType.Json,
    brackets: true,
    unwrap: true,
    args: [
        {
            name: "variable",
            description: "Configuration variable name",
            type: ArgType.String,
            required: true,
            rest: false
        },
        {
            name: "code",
            description: "TOTP code from app",
            type: ArgType.String,
            required: true,
            rest: false
        }
    ],
    async execute(ctx, [variable, code]) {
        const endpoint = "account/two-factor";
        const body = { code };
        const result = await request(variable, "POST", endpoint, body);
        return this.successJSON(result);
    }
});